### ISSUE TITLE
Minified source

### ISSUE THREAD

**Issue by hkdobrev** [mavoweb/mavo.io#26]
Hi, I've noticed some issues with the minified sources when looking at the website:

1. Most places in the docs advertise https://get.mavo.io/mavo.js. However, it's not fully minified. It seems a library called Stretchy bundled inside is not minified.
2. http://mavo.io/get/ is a page linked from the homepage. It advertises using https://get.mavo.io/mavo.minify.js The URL looks like it would be minified, but it actually results in 404. Same with other resources from that page: https://get.mavo.io/mavo.es5.minify.js, https://dev.mavo.io/dist/mavo.es5.minify.js etc.

**Comment by LeaVerou** [comment]
1. https://get.mavo.io/mavo.js is not supposed to be minified though some bundled dependencies are
2. Ouch, that was indeed a bug, caused by taking down the minified version too hastily. Should be fixed now, thanks!
3. The minified version will be up soon, it was taken down because it was discovered that it had bugs not present in regular Mavo.
