### ISSUE TITLE
Storage attributes

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo.io#97]
We should document the change that https://github.com/mavoweb/mavo/issues/657 introduced. 

And https://github.com/mavoweb/mavo/issues/664 https://github.com/mavoweb/mavo/issues/665 once they are resolved.

We should write the section keeping in mind that plugins can link to it instead of having to explain what these are (and deal with the awkwardness of saying "`mv-storage-*` (and `mv-source-*`, and `mv-init-*`, and `mv-upload-*`)")

**Comment by DmitrySharabin** [comment]
A couple of things to consider and not to forget to correct:

- In the [Creating your own storage backend](https://mavo.io/docs/storage#creating-your-own-storage-backend) section, we need to update the constructor signature and the description of the properties defined by the parent constructor (`options`, `key`, etc.)
- In the `getUser()` method replace `mavo:login` with `mavo-login`.

Should we rewrite code snippets with `async/await` instead of `promise.then().catch()`?

**Comment by LeaVerou** [comment]
> Should we rewrite code snippets with `async/await` instead of `promise.then().catch()`?

Only when it makes them more readable.

**Comment by DmitrySharabin** [comment]
Since the corresponding PR is merged, I believe we can now close this issue.
